// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EF_AdvectureWorks.Models;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EF_AdvectureWorks.Models.Configurations
{
    public partial class VJobCandidateEmploymentConfiguration : IEntityTypeConfiguration<VJobCandidateEmployment>
    {
        public void Configure(EntityTypeBuilder<VJobCandidateEmployment> entity)
        {
            entity
            .HasNoKey()
            .ToView("vJobCandidateEmployment", "HumanResources");

            entity.Property(e => e.EmpEndDate)
            .HasColumnType("datetime")
            .HasColumnName("Emp.EndDate");
            entity.Property(e => e.EmpFunctionCategory).HasColumnName("Emp.FunctionCategory");
            entity.Property(e => e.EmpIndustryCategory).HasColumnName("Emp.IndustryCategory");
            entity.Property(e => e.EmpJobTitle)
            .HasMaxLength(100)
            .HasColumnName("Emp.JobTitle");
            entity.Property(e => e.EmpLocCity).HasColumnName("Emp.Loc.City");
            entity.Property(e => e.EmpLocCountryRegion).HasColumnName("Emp.Loc.CountryRegion");
            entity.Property(e => e.EmpLocState).HasColumnName("Emp.Loc.State");
            entity.Property(e => e.EmpOrgName)
            .HasMaxLength(100)
            .HasColumnName("Emp.OrgName");
            entity.Property(e => e.EmpResponsibility).HasColumnName("Emp.Responsibility");
            entity.Property(e => e.EmpStartDate)
            .HasColumnType("datetime")
            .HasColumnName("Emp.StartDate");
            entity.Property(e => e.JobCandidateId)
            .ValueGeneratedOnAdd()
            .HasColumnName("JobCandidateID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VJobCandidateEmployment> entity);
    }
}
