// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EF_AdvectureWorks.Models;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EF_AdvectureWorks.Models.Configurations
{
    public partial class VPersonDemographicsConfiguration : IEntityTypeConfiguration<VPersonDemographics>
    {
        public void Configure(EntityTypeBuilder<VPersonDemographics> entity)
        {
            entity
            .HasNoKey()
            .ToView("vPersonDemographics", "Sales");

            entity.Property(e => e.BirthDate).HasColumnType("datetime");
            entity.Property(e => e.BusinessEntityId).HasColumnName("BusinessEntityID");
            entity.Property(e => e.DateFirstPurchase).HasColumnType("datetime");
            entity.Property(e => e.Education).HasMaxLength(30);
            entity.Property(e => e.Gender).HasMaxLength(1);
            entity.Property(e => e.MaritalStatus).HasMaxLength(1);
            entity.Property(e => e.Occupation).HasMaxLength(30);
            entity.Property(e => e.TotalPurchaseYtd)
            .HasColumnType("money")
            .HasColumnName("TotalPurchaseYTD");
            entity.Property(e => e.YearlyIncome).HasMaxLength(30);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VPersonDemographics> entity);
    }
}
