// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EF_AdvectureWorks.Models;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EF_AdvectureWorks.Models.Configurations
{
    public partial class VStateProvinceCountryRegionConfiguration : IEntityTypeConfiguration<VStateProvinceCountryRegion>
    {
        public void Configure(EntityTypeBuilder<VStateProvinceCountryRegion> entity)
        {
            entity
            .HasNoKey()
            .ToView("vStateProvinceCountryRegion", "Person");

            entity.Property(e => e.CountryRegionCode).HasMaxLength(3);
            entity.Property(e => e.CountryRegionName).HasMaxLength(50);
            entity.Property(e => e.StateProvinceCode)
            .HasMaxLength(3)
            .IsFixedLength();
            entity.Property(e => e.StateProvinceId).HasColumnName("StateProvinceID");
            entity.Property(e => e.StateProvinceName).HasMaxLength(50);
            entity.Property(e => e.TerritoryId).HasColumnName("TerritoryID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VStateProvinceCountryRegion> entity);
    }
}
