// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;


namespace EF_AdvectureWorks.Models.HumanResourcesSchema;

public partial class VJobCandidateEmployment
{
    public int JobCandidateId { get; set; }

    public DateTime? EmpStartDate { get; set; }

    public DateTime? EmpEndDate { get; set; }

    public string? EmpOrgName { get; set; }

    public string? EmpJobTitle { get; set; }

    public string? EmpResponsibility { get; set; }

    public string? EmpFunctionCategory { get; set; }

    public string? EmpIndustryCategory { get; set; }

    public string? EmpLocCountryRegion { get; set; }

    public string? EmpLocState { get; set; }

    public string? EmpLocCity { get; set; }
}