// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;


namespace EF_AdvectureWorks.Models.PersonSchema;

public partial class VStateProvinceCountryRegion
{
    public int StateProvinceId { get; set; }

    public string StateProvinceCode { get; set; } = null!;

    public bool IsOnlyStateProvinceFlag { get; set; }

    public string StateProvinceName { get; set; } = null!;

    public int TerritoryId { get; set; }

    public string CountryRegionCode { get; set; } = null!;

    public string CountryRegionName { get; set; } = null!;
}