// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EF_AdvectureWorks.Models;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EF_AdvectureWorks.Models.Configurations
{
    public partial class VAdditionalContactInfoConfiguration : IEntityTypeConfiguration<VAdditionalContactInfo>
    {
        public void Configure(EntityTypeBuilder<VAdditionalContactInfo> entity)
        {
            entity
            .HasNoKey()
            .ToView("vAdditionalContactInfo", "Person");

            entity.Property(e => e.BusinessEntityId).HasColumnName("BusinessEntityID");
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.CountryRegion).HasMaxLength(50);
            entity.Property(e => e.EmailAddress)
            .HasMaxLength(128)
            .HasColumnName("EMailAddress");
            entity.Property(e => e.EmailSpecialInstructions).HasColumnName("EMailSpecialInstructions");
            entity.Property(e => e.EmailTelephoneNumber)
            .HasMaxLength(50)
            .HasColumnName("EMailTelephoneNumber");
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.MiddleName).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PostalCode).HasMaxLength(50);
            entity.Property(e => e.Rowguid).HasColumnName("rowguid");
            entity.Property(e => e.StateProvince).HasMaxLength(50);
            entity.Property(e => e.Street).HasMaxLength(50);
            entity.Property(e => e.TelephoneNumber).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VAdditionalContactInfo> entity);
    }
}
