// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EF_AdvectureWorks.Models;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EF_AdvectureWorks.Models.Configurations
{
    public partial class VSalesPersonSalesByFiscalYearsConfiguration : IEntityTypeConfiguration<VSalesPersonSalesByFiscalYears>
    {
        public void Configure(EntityTypeBuilder<VSalesPersonSalesByFiscalYears> entity)
        {
            entity
            .HasNoKey()
            .ToView("vSalesPersonSalesByFiscalYears", "Sales");

            entity.Property(e => e.FullName).HasMaxLength(152);
            entity.Property(e => e.JobTitle).HasMaxLength(50);
            entity.Property(e => e.SalesPersonId).HasColumnName("SalesPersonID");
            entity.Property(e => e.SalesTerritory).HasMaxLength(50);
            entity.Property(e => e._2002)
            .HasColumnType("money")
            .HasColumnName("2002");
            entity.Property(e => e._2003)
            .HasColumnType("money")
            .HasColumnName("2003");
            entity.Property(e => e._2004)
            .HasColumnType("money")
            .HasColumnName("2004");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VSalesPersonSalesByFiscalYears> entity);
    }
}
