// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EF_AdvectureWorks.Models;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EF_AdvectureWorks.Models.Configurations
{
    public partial class VStoreWithDemographicsConfiguration : IEntityTypeConfiguration<VStoreWithDemographics>
    {
        public void Configure(EntityTypeBuilder<VStoreWithDemographics> entity)
        {
            entity
            .HasNoKey()
            .ToView("vStoreWithDemographics", "Sales");

            entity.Property(e => e.AnnualRevenue).HasColumnType("money");
            entity.Property(e => e.AnnualSales).HasColumnType("money");
            entity.Property(e => e.BankName).HasMaxLength(50);
            entity.Property(e => e.Brands).HasMaxLength(30);
            entity.Property(e => e.BusinessEntityId).HasColumnName("BusinessEntityID");
            entity.Property(e => e.BusinessType).HasMaxLength(5);
            entity.Property(e => e.Internet).HasMaxLength(30);
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.Specialty).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VStoreWithDemographics> entity);
    }
}
