// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace EF_AdvectureWorks.Models.dbo
{
    public partial class uspGetEmployeeManagersResult
    {
        public int? RecursionLevel { get; set; }
        public int? BusinessEntityID { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? OrganizationNode { get; set; }
        public string ManagerFirstName { get; set; } = default!;
        public string ManagerLastName { get; set; } = default!;
    }
}
