// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;


namespace EF_AdvectureWorks.Models.HumanResourcesSchema;

/// <summary>
/// Work shift lookup table.
/// </summary>
public partial class Shift
{
    /// <summary>
    /// Primary key for Shift records.
    /// </summary>
    public byte ShiftId { get; set; }

    /// <summary>
    /// Shift description.
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// Shift start time.
    /// </summary>
    public TimeSpan StartTime { get; set; }

    /// <summary>
    /// Shift end time.
    /// </summary>
    public TimeSpan EndTime { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<EmployeeDepartmentHistory> EmployeeDepartmentHistory { get; set; } = new List<EmployeeDepartmentHistory>();
}