// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EF_AdvectureWorks.Models;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EF_AdvectureWorks.Models.Configurations
{
    public partial class VJobCandidateConfiguration : IEntityTypeConfiguration<VJobCandidate>
    {
        public void Configure(EntityTypeBuilder<VJobCandidate> entity)
        {
            entity
            .HasNoKey()
            .ToView("vJobCandidate", "HumanResources");

            entity.Property(e => e.AddrLocCity)
            .HasMaxLength(100)
            .HasColumnName("Addr.Loc.City");
            entity.Property(e => e.AddrLocCountryRegion)
            .HasMaxLength(100)
            .HasColumnName("Addr.Loc.CountryRegion");
            entity.Property(e => e.AddrLocState)
            .HasMaxLength(100)
            .HasColumnName("Addr.Loc.State");
            entity.Property(e => e.AddrPostalCode)
            .HasMaxLength(20)
            .HasColumnName("Addr.PostalCode");
            entity.Property(e => e.AddrType)
            .HasMaxLength(30)
            .HasColumnName("Addr.Type");
            entity.Property(e => e.BusinessEntityId).HasColumnName("BusinessEntityID");
            entity.Property(e => e.Email).HasColumnName("EMail");
            entity.Property(e => e.JobCandidateId)
            .ValueGeneratedOnAdd()
            .HasColumnName("JobCandidateID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.NameFirst)
            .HasMaxLength(30)
            .HasColumnName("Name.First");
            entity.Property(e => e.NameLast)
            .HasMaxLength(30)
            .HasColumnName("Name.Last");
            entity.Property(e => e.NameMiddle)
            .HasMaxLength(30)
            .HasColumnName("Name.Middle");
            entity.Property(e => e.NamePrefix)
            .HasMaxLength(30)
            .HasColumnName("Name.Prefix");
            entity.Property(e => e.NameSuffix)
            .HasMaxLength(30)
            .HasColumnName("Name.Suffix");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VJobCandidate> entity);
    }
}
