// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using EF_AdvectureWorks.Models.dboSchema;
using EF_AdvectureWorks.Models.HumanResourcesSchema;
using EF_AdvectureWorks.Models.PersonSchema;
using EF_AdvectureWorks.Models.ProductionSchema;
using EF_AdvectureWorks.Models.PurchasingSchema;
using EF_AdvectureWorks.Models.SalesSchema;


namespace EF_AdvectureWorks.Models.SalesSchema;

public partial class VStoreWithDemographics
{
    public int BusinessEntityId { get; set; }

    public string Name { get; set; } = null!;

    public decimal? AnnualSales { get; set; }

    public decimal? AnnualRevenue { get; set; }

    public string? BankName { get; set; }

    public string? BusinessType { get; set; }

    public int? YearOpened { get; set; }

    public string? Specialty { get; set; }

    public int? SquareFeet { get; set; }

    public string? Brands { get; set; }

    public string? Internet { get; set; }

    public int? NumberEmployees { get; set; }
}