version: "3.7"

services:
  pg-db:
    image: postgres:latest
    restart: always
    container_name: pg-db
    hostname: pg-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P@ssw0rd # the username is postgres
    ports:
      - "5432:5432"
    volumes:
      - C:\DockerVolumes\postgres\databases:/usr/databases

  adminer:
    image: adminer:latest
    hostname: pg-adminer
    container_name: pg-adminer
    volumes:
      - C:\DockerVolumes\postgres\databases:/usr/databases
    restart: always
    ports:
      - 8080:8080

  jupyter:
    image: asami76/allspark:latest
    container_name: jupyter
    hostname: jupyter
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - C:\DockerVolumes\postgres\databases:/home/jovyan/
    ports:
      - 8888:8888
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "ahmed.samy@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "P@ssw0rd"
    volumes:
      - C:\DockerVolumes\postgres\databases:/usr/databases
    restart: always
    ports:
      - "5050:80"